update papers set has_bibtex = 1 where id = 938
; update papers set has_bibtex = 1 where id = 704
; update papers set has_bibtex = 1 where id = 704
; update papers set has_bibtex = 1 where id = 706
; update papers set has_bibtex = 1 where id = 705
; update papers set has_bibtex = 1 where id = 707
; update papers set has_bibtex = 1 where id = 715
; update papers set has_bibtex = 1 where id = 714
; update papers set has_bibtex = 1 where id = 720
; update papers set has_bibtex = 1 where id = 730
; update papers set has_bibtex = 1 where id = 711
; update papers set has_bibtex = 1 where id = 1059
; update papers set has_bibtex = 1 where id = 710
; update papers set has_bibtex = 1 where id = 713
; update papers set has_bibtex = 1 where id = 712
; update papers set has_bibtex = 1 where id = 709
; update papers set has_bibtex = 1 where id = 1060
; update papers set has_bibtex = 1 where id = 719
; update papers set has_bibtex = 1 where id = 722
; update papers set has_bibtex = 1 where id = 732
; update papers set has_bibtex = 1 where id = 731
; update papers set has_bibtex = 1 where id = 733
; update papers set has_bibtex = 1 where id = 725
; update papers set has_bibtex = 1 where id = 724
; update papers set has_bibtex = 1 where id = 721
; update papers set has_bibtex = 1 where id = 726
; update papers set has_bibtex = 1 where id = 729
; update papers set has_bibtex = 1 where id = 727
; update papers set has_bibtex = 1 where id = 735
; update papers set has_bibtex = 1 where id = 1099
; update papers set has_bibtex = 1 where id = 744
; update papers set has_bibtex = 1 where id = 761
; update papers set has_bibtex = 1 where id = 736
; update papers set has_bibtex = 1 where id = 909
; update papers set has_bibtex = 1 where id = 908
; update papers set has_bibtex = 1 where id = 734
; update papers set has_bibtex = 1 where id = 800
; update papers set has_bibtex = 1 where id = 829
; update papers set has_bibtex = 1 where id = 822
; update papers set has_bibtex = 1 where id = 771
; update papers set has_bibtex = 1 where id = 784
; update papers set has_bibtex = 1 where id = 852
; update papers set has_bibtex = 1 where id = 748
; update papers set has_bibtex = 1 where id = 749
; update papers set has_bibtex = 1 where id = 756
; update papers set has_bibtex = 1 where id = 757
; update papers set has_bibtex = 1 where id = 799
; update papers set has_bibtex = 1 where id = 862
; update papers set has_bibtex = 1 where id = 1063
; update papers set has_bibtex = 1 where id = 811
; update papers set has_bibtex = 1 where id = 1065
; update papers set has_bibtex = 1 where id = 737
; update papers set has_bibtex = 1 where id = 768
; update papers set has_bibtex = 1 where id = 815
; update papers set has_bibtex = 1 where id = 805
; update papers set has_bibtex = 1 where id = 738
; update papers set has_bibtex = 1 where id = 741
; update papers set has_bibtex = 1 where id = 740
; update papers set has_bibtex = 1 where id = 781
; update papers set has_bibtex = 1 where id = 779
; update papers set has_bibtex = 1 where id = 871
; update papers set has_bibtex = 1 where id = 897
; update papers set has_bibtex = 1 where id = 746
; update papers set has_bibtex = 1 where id = 750
; update papers set has_bibtex = 1 where id = 752
; update papers set has_bibtex = 1 where id = 754
; update papers set has_bibtex = 1 where id = 753
; update papers set has_bibtex = 1 where id = 766
; update papers set has_bibtex = 1 where id = 776
; update papers set has_bibtex = 1 where id = 808
; update papers set has_bibtex = 1 where id = 898
; update papers set has_bibtex = 1 where id = 751
; update papers set has_bibtex = 1 where id = 758
; update papers set has_bibtex = 1 where id = 773
; update papers set has_bibtex = 1 where id = 778
; update papers set has_bibtex = 1 where id = 785
; update papers set has_bibtex = 1 where id = 797
; update papers set has_bibtex = 1 where id = 804
; update papers set has_bibtex = 1 where id = 821
; update papers set has_bibtex = 1 where id = 832
; update papers set has_bibtex = 1 where id = 839
; update papers set has_bibtex = 1 where id = 880
; update papers set has_bibtex = 1 where id = 879
; update papers set has_bibtex = 1 where id = 893
; update papers set has_bibtex = 1 where id = 919
; update papers set has_bibtex = 1 where id = 786
; update papers set has_bibtex = 1 where id = 809
; update papers set has_bibtex = 1 where id = 840
; update papers set has_bibtex = 1 where id = 849
; update papers set has_bibtex = 1 where id = 870
; update papers set has_bibtex = 1 where id = 887
; update papers set has_bibtex = 1 where id = 783
; update papers set has_bibtex = 1 where id = 814
; update papers set has_bibtex = 1 where id = 813
; update papers set has_bibtex = 1 where id = 827
; update papers set has_bibtex = 1 where id = 1100
; update papers set has_bibtex = 1 where id = 1101
; update papers set has_bibtex = 1 where id = 937
; update papers set has_bibtex = 1 where id = 943
; update papers set has_bibtex = 1 where id = 1086
; update papers set has_bibtex = 1 where id = 948
; update papers set has_bibtex = 1 where id = 963
; update papers set has_bibtex = 1 where id = 1006
; update papers set has_bibtex = 1 where id = 1002
; update papers set has_bibtex = 1 where id = 939
; update papers set has_bibtex = 1 where id = 940
; update papers set has_bibtex = 1 where id = 959
; update papers set has_bibtex = 1 where id = 942
; update papers set has_bibtex = 1 where id = 941
; update papers set has_bibtex = 1 where id = 936
; update papers set has_bibtex = 1 where id = 988
; update papers set has_bibtex = 1 where id = 1009
; update papers set has_bibtex = 1 where id = 1093
; update papers set has_bibtex = 1 where id = 1008
; update papers set has_bibtex = 1 where id = 959
; update papers set has_bibtex = 1 where id = 951
; update papers set has_bibtex = 1 where id = 958
; update papers set has_bibtex = 1 where id = 979
; update papers set has_bibtex = 1 where id = 995
; update papers set has_bibtex = 1 where id = 1030
; update papers set has_bibtex = 1 where id = 1023
; update papers set has_bibtex = 1 where id = 1093
; update papers set has_bibtex = 1 where id = 1018
; update papers set has_bibtex = 1 where id = 952
; update papers set has_bibtex = 1 where id = 1068
; update papers set has_bibtex = 1 where id = 991
; update papers set has_bibtex = 1 where id = 993
; update papers set has_bibtex = 1 where id = 1094
; update papers set has_bibtex = 1 where id = 1047
; update papers set has_bibtex = 1 where id = 1088
; update papers set has_bibtex = 1 where id = 1012
; update papers set has_bibtex = 1 where id = 1021
; update papers set has_bibtex = 1 where id = 1103
; update papers set has_bibtex = 1 where id = 1035
; update papers set has_bibtex = 1 where id = 1092
; update papers set has_bibtex = 1 where id = 1032
; update papers set has_bibtex = 1 where id = 1039
; update papers set has_bibtex = 1 where id = 1058
; update papers set has_bibtex = 1 where id = 1098
; update papers set has_bibtex = 1 where id = 1097
; update papers set has_bibtex = 1 where id = 960
; update papers set has_bibtex = 1 where id = 980
; update papers set has_bibtex = 1 where id = 1040
; update papers set has_bibtex = 1 where id = 1102
; update papers set has_bibtex = 1 where id = 1043;
